name: tekartik_app_camera_support
description: App camera support
version: 0.1.0
deploy_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  process_run: '>=0.10.8'

dependency_overrides:
  pedantic: '>=1.9.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'