name: tekartik_camera_web
description: Camera web utilities

deploy_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2

dependency_overrides:
  pedantic: '>=1.9.0'

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  process_run:
  test: