name: tekartik_camera_web
description: Camera web utilities
version: '0.1.0'
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js:
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety

dependency_overrides:
  # pedantic: '>=1.9.0'

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  process_run:
  test:
  dev_test: '>=0.13.4+4'